{% set version = "1.4-2" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-qpcr
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/qpcR_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/qpcR/qpcR_{{ version }}.tar.gz
  sha256: 9f6d37187950045db91defbb4e82764e0ee677fecf3c6ec73257aa9e88900413

build:
  skip: true  # [osx]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ stdlib("c") }}                # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ stdlib("m2w64_c") }}          # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]
    - {{ cdt('libselinux') }}  # [linux]
    - {{ cdt('libxdamage') }}  # [linux]
    - {{ cdt('libxxf86vm') }}  # [linux]
    - xorg-libxfixes  # [linux]
  host:
    - r-base
    - r-mass
    - r-matrix
    - r-minpack.lm
    - r-rgl
    - r-robustbase
  run:
    - r-base
    - r-mass
    - r-matrix
    - r-minpack.lm
    - r-rgl
    - r-robustbase

test:
  commands:
    - LD_LIBRARY_PATH=${BUILD_PREFIX}/x86_64-conda-linux-gnu/sysroot/usr/lib64:${BUILD_PREFIX}/lib $R -e "library('qpcR')"           # [not win]
    - "\"%R%\" -e \"library('qpcR')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=qpcR
  license: GPL-2.0-or-later
  summary: Model fitting, optimal model selection and calculation of various features that are essential in the analysis of quantitative real-time polymerase chain reaction (qPCR).
  license_family: GPL2
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: qpcR
# Type: Package
# LazyLoad: yes
# LazyData: yes
# Title: Modelling and Analysis of Real-Time PCR Data
# Version: 1.4-1
# Date: 2018-05-29
# Author: Andrej-Nikolai Spiess <a.spiess@uke.uni-hamburg.de>
# Maintainer: Andrej-Nikolai Spiess <a.spiess@uke.uni-hamburg.de>
# Description: Model fitting, optimal model selection and calculation of various features that are essential in the analysis of quantitative real-time polymerase chain reaction (qPCR).
# License: GPL (>= 2)
# Depends: R (>= 2.13.0), MASS, minpack.lm, rgl, robustbase, Matrix
# NeedsCompilation: yes
# Imports: methods
# Repository: CRAN
# Packaged: 2018-06-05 07:13:24 UTC; anspiess
# Date/Publication: 2018-06-14 10:58:00 UTC
